# Generated by Django 4.1.7 on 2023-02-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='storedpasswords',
            name='account',
            field=models.BinaryField(editable=True, max_length=1024),
        ),
    ]
