# Generated by Django 3.0.3 on 2021-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedpasswords',
            name='account',
            field=models.BinaryField(editable=True, max_length=1024),
        ),
    ]
